apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: start-samtale-microfrontend
  namespace: dab
  labels:
    team: dab
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: start-samtale-microfrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: start-samtale-microfrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: start-samtale-microfrontend/internal/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://www.intern.dev.nav.no/dab/start-samtale-microfrontend"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi